### ISSUE TITLE
Similar Paper

### ISSUE THREAD

**Issue by sunstarchan** [hlesmqh/WS3D#1]
First I would like to say great work. 

And I notice there is another paper called 

**Weakly Supervised 3D Object Detection from Point Clouds**
https://arxiv.org/pdf/2007.13970.pdf

which is very similar with yours. So what's the main difference? 
I'll try to figure out the basic ideas of these two papers.

**Comment by wenguanwang** [comment]
@sunstarchan Thanks for your interest. Just happen to have a similar title. And the submission and acceptance dates of ECCV are before ACMMM. These two papers are from different groups and I do not notice this work before your reminder : ( The ideas are very different. For more details, you should better go deep into the papers.
