### ISSUE TITLE
Projecting from BEV to Point Cloud 

### ISSUE THREAD

**Issue by Laihu08** [hlesmqh/WS3D#2]
How to generate the Pseudo front view by projecting from BEV into Pointcloud? 
Can you provide code for that projection only?

**Comment by hlesmqh** [comment]
@Laihu08 Thanks for your attention! I do not quite catch your point. The KITTI dataset has already provided 3D lidar points, front view image as well as the calibration between them. The lidar points on front view is obtained by directly projecting point cloud onto image. And the BEV map is obtained by just compressing the height information of the 3D point cloud. You can find these code in ```/lib/utils/calibration.py```.

**Comment by Laihu08** [comment]
Thanks for replying, my question is, how you guys getting a pseudo front
view(oblique projection) from BEV.

**Comment by hlesmqh** [comment]
@Laihu08 We get pseudo front view from 3D Lidar point cloud data, not from BEV map. The BEV point cloud contains information loss and can not be transformed to front view.

**Comment by Laihu08** [comment]
How you are converting  from point cloud to pseudo view !?

**Comment by hlesmqh** [comment]
@Laihu08 Please read my first reply. You need to download the ```calib``` files of kitti and use the function ```lidar_to_img``` inside ```/lib/utils/calibration.py```.

**Comment by zx970505** [comment]
@Laihu08 @hlesmqh hi,how can i get the lable_w/lable.txt?

**Comment by Laihu08** [comment]
> @Laihu08 @hlesmqh hi,how can i get the lable_w/lable.txt?

you can get label.txt files from the Kitti dataset.

**Comment by zx970505** [comment]
&nbsp;Do you mean the folder named label_2 including files from&nbsp; 000000.txt to 007480.txt?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rahul selvaraj"<notifications@github.com&gt;; 
发送时间: 2020年11月16日(星期一) 中午12:07
收件人: "hlesmqh/WS3D"<WS3D@noreply.github.com&gt;; 
抄送: "墨北"<2293088324@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [hlesmqh/WS3D] Projecting from BEV to Point Cloud  (#2)





  
@Laihu08 @hlesmqh hi,how can i get the lable_w/lable.txt?
  
you can get label.txt files from the Kitti dataset.

**Comment by Laihu08** [comment]
> &nbsp;Do you mean the folder named label_2 including files from&nbsp; 000000.txt to 007480.txt?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Rahul selvaraj"<notifications@github.com&gt;; 发送时间: 2020年11月16日(星期一) 中午12:07 收件人: "hlesmqh/WS3D"<WS3D@noreply.github.com&gt;; 抄送: "墨北"<2293088324@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [hlesmqh/WS3D] Projecting from BEV to Point Cloud (#2) @Laihu08 @hlesmqh hi,how can i get the lable_w/lable.txt? you can get label.txt files from the Kitti dataset. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

yes

**Comment by zx970505** [comment]
@Laihu08 Hi, how can I get the BEV center-click annotation? I can not open the link the author gave.

**Comment by Laihu08** [comment]
That link is to get dataset which was already been Annotated by center
click.  If you want to do by yourself means then you need to follow the
instructions which is given by author.

**Comment by zx970505** [comment]
@Laihu08 It will take me much time,so I want to get the link to the label Annotated. Do you have it ? I can not open the link.

**Comment by Laihu08** [comment]
Even I cannot open the link, need to request author to repost the link.
