### ISSUE TITLE
How to visualize your labelled BEV annotation ?

### ISSUE THREAD

**Issue by Laihu08** [hlesmqh/WS3D#5]
can you provide code to visualize your BEV click annotation?

**Comment by zx970505** [comment]
you can run Pointcloud_Annotation/annotation.py.

**Comment by Laihu08** [comment]
but it showing some Assertion error!

**Comment by wenguanwang** [comment]
@Laihu08  can you provide more details？note that we have no any duty to help you solve this kind of problem. pls be more nice！you are asking for help

**Comment by Laihu08** [comment]
sorry for that I didn't mean that, this is an error which I am getting as I discussed before. Thanks
![Screenshot from 2020-12-02 11-22-24](https://user-images.githubusercontent.com/55731288/100824532-48ba4000-3491-11eb-853f-2a8ab2783fb6.png)

**Comment by zx970505** [comment]
@Laihu08 This error is because the path cannot be found, you can try to add your path to the project. just use this 'sys.path.append'. Or debug the image path.

**Comment by Laihu08** [comment]
> @Laihu08 This error is because the path cannot be found, you can try to add your path to the project. just use this 'sys.path.append'. Or debug the image path.

Thanks for your quick reply, can you guide me to do debug the file path because I am new to this. Thanks

**Comment by zx970505** [comment]
@Laihu08 You can print the path of the image_file first to see if it exists, if it does not exist, modify the path, if it exists, add this path to your project.

**Comment by Laihu08** [comment]
> @Laihu08 You can print the path of the image_file first to see if it exists, if it does not exist, modify the path, if it exists, add this path to your project.

Ok, I will try what you said, thank you. If I have any other problems I'll post here.

**Comment by Laihu08** [comment]
> @Laihu08 You can print the path of the image_file first to see if it exists, if it does not exist, modify the path, if it exists, add this path to your project.

I tried this, still, I am getting the same error. One more thing I downloaded this repository and trying to run the annotation strategy. can you help me out to solve this problem. Thanks in advance
