### ISSUE TITLE
No such file or directory: '/home/rtx-3090/dataset/Kitti/object/ImageSets/small_val.txt'

### ISSUE THREAD

**Issue by shxzhao** [hlesmqh/WS3D#8]
Hi! I cant find the small_val.txt in this project. How can I get it?

**Comment by wanghangege** [comment]
hello, have you solved this problem?

**Comment by hlesmqh** [comment]
@wanghangege That is a small validation set for fast evaluation in our experiment. Please change it to val.txt.

**Comment by wanghangege** [comment]
> @wanghangege That is a small validation set for fast evaluation in our experiment. Please change it to val.txt.

thanks，actually I did as you said.
